(() => {
  const money = new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
  const euroMoney = new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR'});
  const dateFmt = new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short'});
  let status={initialized:false,user:null}, data={}, uploadedImages=[], map, routeLine, markers=[], active={dayId:null,type:null,itemId:null}, aiMode='trip', researchTimer=null, exchangeRate={rate:null,date:null};
  const undoStack=[];
  const defaults = Object.fromEntries((window.DEFAULT_DAYS||[]).map(d=>[d.id,d]));
  const api=async(path,options={})=>{const r=await fetch('/api/'+path,{credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})},...options});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'The request failed.');return j};
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const clone=v=>JSON.parse(JSON.stringify(v));
  const settings=()=>data.__settings ||= {title:'Netherlands & Germany',startDate:'2026-08-12',endDate:'2026-08-27',vehicle:'Ford Explorer EV'};
  const edits=()=>data.__days ||= {};
  const bookings=id=>data[id] ||= {attractions:[],accommodations:[],ferries:[]};
  const currentDay=id=>({...defaults[id],...(edits()[id]||{}),id});
  const sortedDays=()=>Object.keys(defaults).map(currentDay).sort((a,b)=>String(a.dateISO).localeCompare(String(b.dateISO))||a.id.localeCompare(b.id));
  const currencyOf=item=>item?.currency==='EUR'?'EUR':'GBP';
  const currencyMoney=(value,currency='GBP')=>(currency==='EUR'?euroMoney:money).format(num(value));
  const lineCost=item=>num(item?.totalCost ?? item?.cost);
  const addCurrency=(totals,item)=>{totals[currencyOf(item)]+=lineCost(item);return totals};
  const dayTotals=id=>{const b=bookings(id),totals={GBP:0,EUR:0};[...(b.attractions||[]),...(b.accommodations||[]),...(b.ferries||[])].forEach(x=>addCurrency(totals,x));return totals};
  const sterlingEstimate=totals=>totals.GBP+(exchangeRate.rate?totals.EUR*exchangeRate.rate:0);
  const totalsText=totals=>[totals.GBP?money.format(totals.GBP):'',totals.EUR?euroMoney.format(totals.EUR):''].filter(Boolean).join(' + ')||money.format(0);
  const dayCost=id=>sterlingEstimate(dayTotals(id));
  function toast(message,undo=true){const t=document.getElementById('toast');document.getElementById('toast-text').textContent=message;document.getElementById('toast-undo').hidden=!undo;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),6000)}
  function pushUndo(label){undoStack.push({label,data:clone(data)});if(undoStack.length>30)undoStack.shift()}
  async function undo(){const snap=undoStack.pop();if(!snap){try{const r=await api('history/undo',{method:'POST',body:'{}'});data=r.data||{};await renderAll();toast('Restored the previous saved version.',false)}catch(e){toast(e.message,false)}return}data=snap.data;await saveData(false);toast(`Undid: ${snap.label}`,false)}
  async function saveData(show=true){if(status.user?.role!=='admin')throw new Error('This account has read-only access.');await api('data',{method:'PUT',body:JSON.stringify({data})});await renderAll();if(show)toast('Changes saved.');}
  async function loadData(){const [d,im,fx]=await Promise.all([api('data',{method:'GET'}),api('images',{method:'GET'}).catch(()=>({images:[]})),api('currency-rate',{method:'GET'}).catch(()=>({rate:null,date:null}))]);data=d.data||{};uploadedImages=im.images||[];exchangeRate={rate:num(fx.rate)||null,date:fx.date||null};await renderAll()}

  // Authentication
  const authScreen=document.getElementById('auth-screen'),authForm=document.getElementById('auth-form'),authError=document.getElementById('auth-error');
  function setAuthMode(){const setup=!status.initialized;document.getElementById('auth-title').textContent=setup?'Create administrator':'Sign in';document.getElementById('auth-intro').textContent=setup?'Create the first administrator account.':'Sign in to the shared trip.';document.getElementById('auth-submit').textContent=setup?'Create account':'Sign in';document.getElementById('auth-confirm-wrap').hidden=!setup;document.getElementById('auth-confirm').required=setup}
  function unlock(user){status.user=user;status.initialized=true;authScreen.hidden=true;document.body.classList.toggle('read-only',user.role!=='admin');document.getElementById('signed-in-user').textContent=user.username;document.getElementById('access-badge').textContent=user.role==='admin'?'Admin':'Read only';document.getElementById('manage-users').hidden=user.role!=='admin';loadData().catch(e=>alert(e.message));loadAssistant().catch(()=>{})}
  function lock(){status.user=null;authScreen.hidden=false;authForm.reset();authError.textContent='';setAuthMode()}
  authForm.addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';try{const username=authForm.username.value.trim(),password=authForm.password.value;let r;if(!status.initialized){if(password!==authForm.confirm.value)throw new Error('Passwords do not match.');r=await api('setup',{method:'POST',body:JSON.stringify({username,password})})}else r=await api('login',{method:'POST',body:JSON.stringify({username,password})});unlock(r.user)}catch(err){authError.textContent=err.message}});
  document.getElementById('logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST',body:'{}'})}catch{}lock()});
  api('status',{method:'GET'}).then(r=>{status=r;r.user?unlock(r.user):lock()}).catch(lock);

  // Navigation
  function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('.side-link').forEach(a=>a.classList.toggle('active',a.dataset.page===name));document.getElementById('page-title').textContent=document.querySelector(`.side-link[data-page="${name}"]`)?.textContent||'Holiday Planner';document.getElementById('sidebar').classList.remove('open');if(name==='overview')setTimeout(()=>map?.invalidateSize(),100)}
  document.querySelectorAll('.side-link').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPage(a.dataset.page);history.replaceState(null,'','#'+a.dataset.page)}));
  document.getElementById('mobile-menu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));

  function dateText(iso){const d=new Date(`${iso}T12:00:00`);return Number.isNaN(d.getTime())?iso:dateFmt.format(d)}
  function flags(id){const b=bookings(id);return {a:(b.accommodations||[]).length>0,t:(b.ferries||[]).length>0,x:(b.attractions||[]).length>0}}
  function statusPill(ok,label){return `<span class="status ${ok?'ok':''}">${ok?'✓':'!'} ${label}</span>`}
  function renderOverview(){const days=sortedDays(),totals=categoryTotals(),count=days.reduce((s,d)=>{const b=bookings(d.id);return s+b.attractions.length+b.accommodations.length+b.ferries.length},0);document.getElementById('summary-days').textContent=days.length;document.getElementById('summary-booked').textContent=count;document.getElementById('summary-total').textContent=money.format(sterlingEstimate(totals.total));document.getElementById('welcome-message').textContent=`Welcome ${status.user?.username||''}`;const start=new Date(`${settings().startDate}T00:00:00`),diff=Math.ceil((start-new Date())/86400000);document.getElementById('holiday-countdown').textContent=diff>0?`${diff} days to go`:diff===0?'The holiday starts today':'Trip date has passed';const fxNote=exchangeRate.rate?`<div class="small">Estimated sterling total uses €1 = ${money.format(exchangeRate.rate)} (${esc(exchangeRate.date||'latest rate')}).</div>`:'<div class="small">Euro costs are shown separately because the exchange rate is unavailable.</div>';document.getElementById('overview-costs').innerHTML=`<div class="budget-row"><span>Sterling costs</span><strong>${money.format(totals.total.GBP)}</strong></div><div class="budget-row"><span>Euro costs</span><strong>${euroMoney.format(totals.total.EUR)}</strong></div><div class="budget-row"><span>Estimated total in sterling</span><strong>${money.format(sterlingEstimate(totals.total))}</strong></div>${fxNote}`;const gap=days.find(d=>{const f=flags(d.id);return !f.a||!f.t||!f.x});document.getElementById('next-gap').textContent=gap?`Next planning gap: ${dateText(gap.dateISO)} — ${gap.title}`:'All days have accommodation, travel and attraction entries.'}
  function renderItineraryOverview(){document.getElementById('overview-body').innerHTML=sortedDays().map(d=>{const f=flags(d.id);return `<tr><td>${esc(dateText(d.dateISO))}</td><td><a href="#breakdown" data-open-day="${d.id}"><strong>${esc(d.title)}</strong></a><br><span class="small">${esc(d.destination||'')}</span></td><td>${statusPill(f.a,f.a?'Added':'Missing')}</td><td>${statusPill(f.t,f.t?'Added':'Missing')}</td><td>${statusPill(f.x,f.x?'Added':'Missing')}</td><td>${totalsText(dayTotals(d.id))}</td></tr>`}).join('');document.querySelectorAll('[data-open-day]').forEach(a=>a.addEventListener('click',()=>{showPage('breakdown');setTimeout(()=>document.querySelector(`[data-day-id="${a.dataset.openDay}"]`)?.scrollIntoView({behavior:'smooth'}),50)}))}
  function renderCalendar(){const grid=document.getElementById('calendar-grid');grid.innerHTML=sortedDays().map((d,i)=>`<article class="calendar-day" draggable="${status.user?.role==='admin'}" data-cal-id="${d.id}"><div class="calendar-date">${esc(dateText(d.dateISO))}</div><div class="calendar-title">${esc(d.title)}</div><div class="calendar-meta">${esc(d.destination||'')}<br>${esc(d.sleeping?`Sleep: ${d.sleeping}`:'')}</div><div class="calendar-actions admin-only"><button data-move="-1" data-id="${d.id}" ${i===0?'disabled':''}>←</button><button data-edit-day="${d.id}">Edit</button><button data-move="1" data-id="${d.id}" ${i===sortedDays().length-1?'disabled':''}>→</button></div></article>`).join('');wireCalendar()}
  function applyCalendarOrder(ids){const dates=sortedDays().map(d=>d.dateISO).sort();ids.forEach((id,index)=>{edits()[id]={...(edits()[id]||{}),dateISO:dates[index]}})}
  async function moveCalendarDay(sourceId,targetId){const ids=sortedDays().map(d=>d.id),from=ids.indexOf(sourceId),to=ids.indexOf(targetId);if(from<0||to<0||from===to)return;ids.splice(from,1);ids.splice(to,0,sourceId);pushUndo('calendar reorder');applyCalendarOrder(ids);await saveData();toast('Calendar order updated throughout the itinerary.')}
  function wireCalendar(){let dragged=null;document.querySelectorAll('.calendar-day').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card.dataset.calId;card.classList.add('dragging')});card.addEventListener('dragend',()=>{card.classList.remove('dragging');dragged=null});card.addEventListener('dragover',e=>{e.preventDefault();card.classList.add('dragover')});card.addEventListener('dragleave',()=>card.classList.remove('dragover'));card.addEventListener('drop',async e=>{e.preventDefault();card.classList.remove('dragover');const source=dragged,target=card.dataset.calId;if(source&&source!==target)await moveCalendarDay(source,target)})});document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',async()=>{const days=sortedDays(),i=days.findIndex(d=>d.id===b.dataset.id),j=i+Number(b.dataset.move);if(j<0||j>=days.length)return;const ids=days.map(d=>d.id);[ids[i],ids[j]]=[ids[j],ids[i]];pushUndo('calendar move');applyCalendarOrder(ids);await saveData();toast('Calendar order updated throughout the itinerary.')}));document.querySelectorAll('[data-edit-day]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.editDay,'day')))}
  function bookingHtml(type,item){const name=item.name||item.operator||item.route||'Entry';const cost=item.totalCost??item.cost;return `<div class="booking-card"><strong>${esc(name)}</strong>${cost!==''&&cost!=null?` — ${currencyMoney(cost,currencyOf(item))}`:''}<br><small>${esc(item.reference||item.notes||'')}</small><div class="admin-only"><button class="btn secondary" data-edit-entry="${esc(type)}" data-entry-id="${esc(item.id)}">Edit</button> <button class="btn danger" data-delete-entry="${esc(type)}" data-entry-id="${esc(item.id)}">Delete</button></div></div>`}
  function renderBreakdown(){const timeline=document.getElementById('timeline');timeline.innerHTML=sortedDays().map((d,i)=>{const b=bookings(d.id),imgs=(d.images&&d.images.length?d.images:[{url:d.imageUrl||'',alt:d.imageAlt||d.title}]).filter(x=>x.url);return `<article class="day" data-day-id="${d.id}">${imgs.length?`<div class="day-media">${imgs.map(x=>`<img src="${esc(x.url)}" alt="${esc(x.alt||d.title)}">`).join('')}</div>`:''}<div class="day-body"><div class="day-head"><div><div class="date">Day ${i+1} • ${esc(dateText(d.dateISO))}</div><h3>${esc(d.title)}</h3></div><div><button class="btn secondary" data-collapse="${d.id}">Collapse</button> <button class="btn admin-only" data-edit-day="${d.id}">Edit day</button></div></div><div class="meta"><span class="tag">${esc(d.drivingDistance||'No travel estimate')}</span>${d.destinationCharge?'<span class="tag charge">Charging planned</span>':''}${d.sleeping?`<span class="tag overnight">Sleep: ${esc(d.sleeping)}</span>`:''}</div><p>${esc(d.summary||'')}</p><div class="day-extra"><div class="toolbar admin-only"><button class="btn secondary" data-add="attraction" data-day="${d.id}">+ Attraction</button><button class="btn secondary" data-add="accommodation" data-day="${d.id}">+ Accommodation</button><button class="btn secondary" data-add="transport" data-day="${d.id}">+ Transport</button></div><div class="planner-summary">${b.attractions.map(x=>bookingHtml('attractions',x)).join('')}${b.accommodations.map(x=>bookingHtml('accommodations',x)).join('')}${b.ferries.map(x=>bookingHtml('ferries',x)).join('')||'<div class="small">No booking details added.</div>'}</div></div></div></article>`}).join('');wireBreakdown()}
  function wireBreakdown(){document.querySelectorAll('[data-edit-day]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.editDay,'day')));document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.day,b.dataset.add)));document.querySelectorAll('[data-collapse]').forEach(b=>b.addEventListener('click',()=>{const a=document.querySelector(`[data-day-id="${b.dataset.collapse}"]`);a.classList.toggle('collapsed');b.textContent=a.classList.contains('collapsed')?'Expand':'Collapse'}));document.querySelectorAll('[data-edit-entry]').forEach(b=>b.addEventListener('click',()=>{const day=b.closest('.day').dataset.dayId,item=bookings(day)[b.dataset.editEntry].find(x=>x.id===b.dataset.entryId);openModal(day,b.dataset.editEntry==='ferries'?'transport':b.dataset.editEntry.slice(0,-1),item)}));document.querySelectorAll('[data-delete-entry]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Delete this entry?'))return;const day=b.closest('.day').dataset.dayId;pushUndo('delete booking');bookings(day)[b.dataset.deleteEntry]=bookings(day)[b.dataset.deleteEntry].filter(x=>x.id!==b.dataset.entryId);await saveData()}))}
  function allBookings(){return sortedDays().flatMap(d=>{const b=bookings(d.id);return [...b.attractions.map(x=>({day:d,type:'Attraction',x,cost:x.cost})),...b.accommodations.map(x=>({day:d,type:'Accommodation',x,cost:x.totalCost||x.cost})),...b.ferries.map(x=>({day:d,type:'Travel',x,cost:x.cost}))]})}
  function renderBookings(){document.getElementById('bookings-body').innerHTML=allBookings().map(({day,type,x,cost})=>`<tr><td>${esc(dateText(day.dateISO))}</td><td>${type}</td><td>${esc(x.name||x.operator||x.route||'Entry')}</td><td>${esc(x.reference||'—')}</td><td>${currencyMoney(cost,currencyOf(x))}</td><td>${statusPill(Boolean(x.reference),x.reference?'Booked':'Planning')}</td></tr>`).join('')||'<tr><td colspan="6">No bookings added yet.</td></tr>'}
  function categoryTotals(){const result={attractions:{GBP:0,EUR:0},accommodation:{GBP:0,EUR:0},transport:{GBP:0,EUR:0},total:{GBP:0,EUR:0}};sortedDays().forEach(d=>{const b=bookings(d.id);b.attractions.forEach(x=>addCurrency(result.attractions,x));b.accommodations.forEach(x=>addCurrency(result.accommodation,x));b.ferries.forEach(x=>addCurrency(result.transport,x))});for(const c of ['GBP','EUR'])result.total[c]=result.attractions[c]+result.accommodation[c]+result.transport[c];return result}
  function renderBudget(){const t=categoryTotals(),fx=exchangeRate.rate?`<p class="small">Conversion estimate: €1 = ${money.format(exchangeRate.rate)}, rate dated ${esc(exchangeRate.date||'latest')}.</p>`:'<p class="small">Live EUR to GBP rate unavailable; euro totals are not included in the sterling estimate.</p>';document.getElementById('budget-summary').innerHTML=`<h3>Trip totals</h3><div class="stat"><strong>${money.format(t.total.GBP)}</strong>sterling costs</div><div class="stat"><strong>${euroMoney.format(t.total.EUR)}</strong>euro costs</div><div class="stat"><strong>${money.format(sterlingEstimate(t.total))}</strong>estimated total in sterling</div>${fx}<div class="budget-row"><span>Attractions</span><strong>${totalsText(t.attractions)}</strong></div><div class="budget-row"><span>Accommodation</span><strong>${totalsText(t.accommodation)}</strong></div><div class="budget-row"><span>Transport</span><strong>${totalsText(t.transport)}</strong></div>`;document.getElementById('budget-days').innerHTML=sortedDays().filter(d=>{const t=dayTotals(d.id);return t.GBP||t.EUR}).map(d=>{const t=dayTotals(d.id);return `<div class="budget-row"><span>${esc(dateText(d.dateISO))} — ${esc(d.title)}</span><strong>${totalsText(t)}<br><small>≈ ${money.format(sterlingEstimate(t))}</small></strong></div>`}).join('')||'<p class="small">No costs entered.</p>'}
  function renderLibrary(){const items=[...(window.STATIC_IMAGES||[]).map(name=>({name,url:name,source:'Included'})),...uploadedImages.map(x=>({...x,source:'Uploaded'}))];document.getElementById('library-grid').innerHTML=items.map(x=>`<div class="library-item"><img src="${esc(x.url)}" alt="${esc(x.name)}"><div><strong>${esc(x.name)}</strong><br><span class="small">${esc(x.source)}</span></div></div>`).join('')}
  function renderSettings(){document.getElementById('trip-title').value=settings().title||'';document.getElementById('trip-start').value=settings().startDate||'';document.getElementById('trip-end').value=settings().endDate||'';document.getElementById('trip-vehicle').value=settings().vehicle||''}
  function renderMap(){if(!window.L)return;if(!map){map=L.map('trip-map',{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map)}markers.forEach(m=>m.remove());markers=[];if(routeLine)routeLine.remove();const pts=[];sortedDays().forEach((d,i)=>{if(!Number.isFinite(Number(d.lat))||!Number.isFinite(Number(d.lng)))return;const p=[Number(d.lat),Number(d.lng)];pts.push(p);const icon=L.divIcon({className:'',html:`<div style="width:28px;height:28px;border-radius:50%;background:#28786f;color:white;display:grid;place-items:center;font-weight:800;border:2px solid white">${i+1}</div>`,iconSize:[28,28],iconAnchor:[14,14]});markers.push(L.marker(p,{icon}).addTo(map).bindPopup(`<strong>${esc(d.title)}</strong><br>${esc(dateText(d.dateISO))}`))});if(pts.length>1)routeLine=L.polyline(pts,{weight:4,opacity:.8,dashArray:'7 7'}).addTo(map);fitMap();setTimeout(()=>map.invalidateSize(),100)}
  function fitMap(){if(markers.length)map.fitBounds(L.latLngBounds(markers.map(m=>m.getLatLng())),{padding:[30,30]})}
  document.getElementById('fit-map').addEventListener('click',fitMap);
  async function renderAll(){renderOverview();renderItineraryOverview();renderCalendar();renderBreakdown();renderBookings();renderBudget();renderLibrary();renderSettings();renderMap()}

  // Modal and editing
  const modal=document.getElementById('planner-modal'),fields=document.getElementById('form-fields');
  const field=(label,name,type='text',full=false,attrs='')=>`<div class="form-field ${full?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${name}" ${attrs}></textarea>`:`<input name="${name}" type="${type}" ${attrs}>`}</div>`;
  const costField=(label,name='cost')=>field(label,name,'number',false,'min="0" step="0.01" inputmode="decimal"');
  const currencyField=()=>`<div class="form-field"><label>Currency</label><select name="currency"><option value="GBP">Sterling (£)</option><option value="EUR">Euro (€)</option></select></div>`;
  function openModal(dayId,type,item=null){active={dayId,type,itemId:item?.id||null};const d=currentDay(dayId);document.getElementById('modal-day').textContent=dateText(d.dateISO);document.getElementById('modal-title').textContent=type==='day'?'Edit day':`${item?'Edit':'Add'} ${type}`;if(type==='day')fields.innerHTML=field('Date','dateISO','date')+field('Day title','title','text',true)+field('Destination','destination','text',true)+field('Driving distance/time','drivingDistance','text',true)+field('Where sleeping','sleeping')+`<div class="form-field"><label>Charge required</label><select name="destinationCharge"><option value="no">No</option><option value="yes">Yes</option></select></div>`+field('Latitude','lat','number')+field('Longitude','lng','number')+field('Summary','summary','textarea',true)+field('Image URL','imageUrl','text',true);else if(type==='attraction')fields.innerHTML=field('Name','name','text',true)+field('Date','date','date')+costField('Cost')+currencyField()+field('Reference','reference')+field('URL','url','url',true)+field('Notes','notes','textarea',true);else if(type==='accommodation')fields.innerHTML=field('Name','name','text',true)+field('Address','address','textarea',true)+field('Check in','checkIn','date')+field('Nights','nights','number',false,'min="1" step="1"')+costField('Cost per night','nightlyCost')+currencyField()+field('Reference','reference')+field('Notes','notes','textarea',true);else fields.innerHTML=field('Operator/type','operator')+field('Route/description','route','text',true)+field('Departure','departure','datetime-local')+field('Arrival','arrival','datetime-local')+costField('Cost')+currencyField()+field('Reference','reference')+field('Notes','notes','textarea',true);const values=type==='day'?d:{currency:'GBP',...(item||{})};Object.entries(values).forEach(([k,v])=>{const el=fields.querySelector(`[name="${CSS.escape(k)}"]`);if(el)el.value=typeof v==='boolean'?(v?'yes':'no'):(v??'')});modal.classList.add('open')}
  document.querySelector('.modal-close').addEventListener('click',()=>modal.classList.remove('open'));document.querySelector('.cancel-entry').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
  document.getElementById('planner-form').addEventListener('submit',async e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target).entries());pushUndo(active.type==='day'?'edit day':'edit booking');if(active.type==='day'){obj.destinationCharge=obj.destinationCharge==='yes';obj.lat=obj.lat===''?null:Number(obj.lat);obj.lng=obj.lng===''?null:Number(obj.lng);if(obj.imageUrl)obj.images=[{url:obj.imageUrl,alt:obj.title}];edits()[active.dayId]={...(edits()[active.dayId]||{}),...obj}}else{const type=active.type==='transport'?'ferries':active.type+'s',arr=bookings(active.dayId)[type];obj.id=active.itemId||crypto.randomUUID();obj.currency=obj.currency==='EUR'?'EUR':'GBP';if('cost' in obj)obj.cost=Math.round(num(obj.cost)*100)/100;if('nightlyCost' in obj)obj.nightlyCost=Math.round(num(obj.nightlyCost)*100)/100;if(active.type==='accommodation')obj.totalCost=Math.round(num(obj.nightlyCost)*Math.max(1,num(obj.nights))*100)/100;const idx=arr.findIndex(x=>x.id===obj.id);idx>=0?arr[idx]=obj:arr.push(obj)}modal.classList.remove('open');await saveData()});
  document.getElementById('expand-all').addEventListener('click',()=>document.querySelectorAll('.day').forEach(x=>x.classList.remove('collapsed')));document.getElementById('collapse-all').addEventListener('click',()=>document.querySelectorAll('.day').forEach(x=>x.classList.add('collapsed')));document.getElementById('undo-calendar').addEventListener('click',undo);document.getElementById('undo-day').addEventListener('click',undo);document.getElementById('toast-undo').addEventListener('click',undo);
  document.getElementById('save-settings').addEventListener('click',async()=>{pushUndo('trip settings');data.__settings={title:document.getElementById('trip-title').value,startDate:document.getElementById('trip-start').value,endDate:document.getElementById('trip-end').value,vehicle:document.getElementById('trip-vehicle').value};await saveData()});
  document.getElementById('export-data').addEventListener('click',()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='holiday-planner-v5-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)});
  document.getElementById('clear-data').addEventListener('click',async()=>{if(!confirm('Clear all saved edits and bookings?'))return;pushUndo('clear data');data={};await saveData()});
  document.getElementById('upload-library').addEventListener('click',async()=>{const file=document.getElementById('library-file').files[0];if(!file)return alert('Choose an image first.');if(file.size>4*1024*1024)return alert('Maximum image size is 4 MB.');const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const r=await api('images',{method:'POST',body:JSON.stringify({name:file.name,mime:file.type,data:dataUrl})});uploadedImages.unshift(r.image);renderLibrary();toast('Image uploaded.',false)});

  // Assistant
  function tripPayload(){return {trip:settings(),days:sortedDays().map((d,i)=>({day:i+1,date:d.dateISO,currentDay:d,bookings:bookings(d.id)}))}}
  function renderMessages(msgs=[]){document.getElementById('ai-transcript').innerHTML=msgs.map(m=>`<div class="ai-message ${m.role}"><strong>${m.role==='user'?'You':'Travel assistant'}</strong><br>${esc(m.text)}</div>`).join('');document.getElementById('ai-transcript').scrollTop=999999}
  async function loadAssistant(){const r=await api('assistant/state',{method:'GET'});renderMessages(r.messages||[]);document.getElementById('ai-memory-status').textContent=r.conversationReady?'Persistent conversation active.':'Conversation will be created on first use.'}
  document.querySelectorAll('.ai-mode').forEach(b=>b.addEventListener('click',()=>{aiMode=b.dataset.aiMode;document.querySelectorAll('.ai-mode').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('ai-question').placeholder=aiMode==='research'?'Ask for current facts or recommendations':aiMode==='plan'?'Describe a proposed itinerary change':'Ask about your saved trip'}));
  async function pollResearch(id){clearTimeout(researchTimer);const r=await api('assistant/research/'+id,{method:'GET'});document.getElementById('ai-answer').textContent=r.status==='complete'?r.answer:r.status==='failed'?r.error:`Research ${r.status}…`;if(['queued','running'].includes(r.status))researchTimer=setTimeout(()=>pollResearch(id),2500);else loadAssistant()}
  document.getElementById('ask-ai').addEventListener('click',async()=>{const q=document.getElementById('ai-question').value.trim();if(!q)return;const btn=document.getElementById('ask-ai');btn.disabled=true;document.getElementById('ai-answer').textContent='Working…';try{if(aiMode==='research'){const r=await api('assistant/research',{method:'POST',body:JSON.stringify({question:q,tripData:tripPayload()})});pollResearch(r.id)}else{const r=await api('assistant/ask',{method:'POST',body:JSON.stringify({question:q,mode:aiMode,tripData:tripPayload()})});document.getElementById('ai-answer').textContent=r.answer;renderMessages(r.messages)}document.getElementById('ai-question').value=''}catch(e){document.getElementById('ai-answer').textContent=e.message}finally{btn.disabled=false}});
  document.getElementById('new-ai-chat').addEventListener('click',async()=>{if(!confirm('Start a new conversation?'))return;await api('assistant/new-chat',{method:'POST',body:'{}'});await loadAssistant()});

  // User management
  const userModal=document.getElementById('user-modal');document.getElementById('manage-users').addEventListener('click',async()=>{await renderUsers();userModal.classList.add('open')});document.querySelector('.manage-close').addEventListener('click',()=>userModal.classList.remove('open'));
  async function renderUsers(){const r=await api('users',{method:'GET'});document.getElementById('user-list').innerHTML=r.users.map(u=>`<div class="user-row"><div><strong>${esc(u.username)}</strong><div class="small">${u.role}</div></div><div><button class="btn secondary" data-role="${u.id}" data-current="${u.role}">${u.role==='admin'?'Make read only':'Make admin'}</button> <button class="btn danger" data-delete="${u.id}">Delete</button></div></div>`).join('');document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',async()=>{await api('users/'+b.dataset.role,{method:'PATCH',body:JSON.stringify({role:b.dataset.current==='admin'?'user':'admin'})});renderUsers()}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(confirm('Delete user?')){await api('users/'+b.dataset.delete,{method:'DELETE'});renderUsers()}}))}
  document.getElementById('add-user-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('users',{method:'POST',body:JSON.stringify({username:document.getElementById('new-username').value,password:document.getElementById('new-password').value,role:document.getElementById('new-role').value})});e.target.reset();renderUsers()}catch(err){document.getElementById('user-error').textContent=err.message}});
  showPage((location.hash||'#overview').slice(1));
})();
